<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <None Update="resource\tx_ui\background.png;resource\tx_ui\gameover.png;resource\tx_ui\jump.png;resource\tx_ui\obstacle.png;resource\tx_ui\run_sheet.png;resource\tx_ui\start.png;resource\sound\hit.wav;resource\sound\jump.wav;resource\sound\score.wav" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
